# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g-np-EBPbhV0QOstG4ZgGvPQ5ZVCIrCF
"""

import random

angka_rahasia = random.randint(1, 10)
tebakan = 0
kesempatan = 3

print("Tebak angka dari 1 sampai 10. Kamu punya 3 kesempatan! >___<")

while tebakan != angka_rahasia and kesempatan > 0:
  tebakan = int(input("Masukkan tebakan kamu: "))
  kesempatan -= 1

  if tebakan < angka_rahasia:
    print("Terlalu kecil :c")
  elif tebakan > angka_rahasia:
    print("Terlalu besar :o")
  else:
    print("YEAY BENAR!")
    break

  print(f"Sisa kesempatan: {kesempatan}")

if tebakan != angka_rahasia:
  print("Game over! Angka yang benar adalah", angka_rahasia)